// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcLEF3qVKllshBtWz-U_Zzg9McV3bTqYA',
    appId: '1:128535788218:web:ac4083fbe2a40e2e73a083',
    messagingSenderId: '128535788218',
    projectId: 'shal-95234',
    authDomain: 'shal-95234.firebaseapp.com',
    storageBucket: 'shal-95234.appspot.com',
    measurementId: 'G-N062TKVGM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAdWNZ479i_tERRifAP0O85Xi1DR5EULk',
    appId: '1:128535788218:android:0271baa82acb0d3c73a083',
    messagingSenderId: '128535788218',
    projectId: 'shal-95234',
    storageBucket: 'shal-95234.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY0Xf3QHX7Y6_HS4pl4mudLG3wqHcOcUQ',
    appId: '1:128535788218:ios:0556ef0bfeb74ec873a083',
    messagingSenderId: '128535788218',
    projectId: 'shal-95234',
    storageBucket: 'shal-95234.appspot.com',
    iosBundleId: 'com.example.shal',
  );
}
